# paths
vowpal-wabbit: /home/romang/tools/vowpal_wabbit
mosesdecoder: /home/romang/tools/mosesdecoder
stanford-pos-tagger: /home/romang/tools/stanford-pos-tagger

# confusion sets
source-cset: a,an,the,
target-cset: a,an,the,

# factors
word-classes: /home/romang/data/wc.classes.gz
factors:
    1: 'pos'
    2: 'awc'

# features
features:
    SourceWordFeature:
    SourceNGramFeature:
    TargetWordFeature:
    BOWFeature:
        window: 4

# training
model: /home/romang/work/gecvw/alice.vw
costs:
    aaa: 0.0
    aab: 1.0
    abb: 0.0
    aba: 4.0
    abc: 1.0

# data
train-sets:
dev-sets:
test-sets:
