# paths
vowpalwabbit: /home/romang/tools/vowpal_wabbit
mosesdecoder: /home/romang/tools/mosesdecoder

# confusion sets
source-cset: a,an,the,
target-cset: a,an,the,

# features
features:
    SourceWordFeature:
    SourceNGramFeature:
    TargetWordFeature:
    BOWFeature:
        window: 4

# training
model: /home/romang/work/gecvw/alice.vw
costs:
    aaa: 0.0
    aab: 1.0
    abb: 0.0
    aba: 4.0
    abc: 1.0
