# paths
vowpal-wabbit: /home/romang/tools/vowpal_wabbit
mosesdecoder: /home/romang/tools/mosesdecoder
stanford-pos-tagger: /home/romang/tools/stanford-pos-tagger

# common settings
threads: 1

# confusion sets
source-cset: a,an,the,
target-cset: a,an,the,

# factors
word-classes: /home/romang/projects/gecvw/data/wc.classes.gz
factors:
    wc:

# features
features:
    - SourceWordFeature
    - SourceWordFeature:
        factor: 2
    - SourceNGramFeature
    - TargetWordFeature
    - BOWFeature:
        window: 4

# training
model: /home/romang/work/gecvw/alice.vw
costs:
    aaa: 0.0
    aab: 1.0
    abb: 0.0
    aba: 4.0
    abc: 1.0

# data
train-set: /home/romang/projects/gecvw/data/alice.txt
dev-set: /home/romang/projects/gecvw/data/test.artordet.m2
test-sets:
    test0: /home/romang/projects/gecvw/data/test.artordet.m2
